SELECT * FROM DEPT;
SELECT * FROM DEPT WHERE dept_name = '총무부';
SELECT * FROM DEPT WHERE dept_id = 10;
SELECT * FROM DEPT WHERE dept_id = 10 OR dept_name = '감사팀';
SELECT * FROM MEMBER;
SELECT * FROM MEMBER WHERE sal BETWEEN 3000 AND 20000;
SELECT * FROM MEMBER WHERE HIRE = '20/11/03';
SELECT * FROM MEMBER WHERE NAME LIKE '김%';
SELECT * FROM MEMBER WHERE NAME LIKE '_주%';
SELECT NAME, HIRE FROM MEMBER;
SELECT HIRE, NAME FROM MEMBER;
SELECT NAME, JIKWI, BONUS FROM MEMBER;
SELECT NAME FROM MEMBER WHERE bonus IS NULL;
SELECT NAME FROM MEMBER WHERE bonus IS NOT NULL;
SELECT NAME AS NAME2 FROM MEMBER;
SELECT NAME AS 이름 FROM MEMBER;
SELECT NAME 이름 FROM MEMBER;
SELECT 
m.NAME,
m.sal
FROM MEMBER m;
SELECT * FROM MEMBER;
SELECT * FROM MEMBER WHERE DEPT_ID = 10;
SELECT * FROM MEMBER WHERE DEPT_ID <> 10;
SELECT * FROM MEMBER WHERE DEPT_ID != 10;
SELECT * FROM MEMBER WHERE DEPT_ID IN (10, 30);
SELECT * FROM MEMBER WHERE DEPT_ID = 10 OR DEPT_ID = 30;
SELECT * FROM DEPT
UNION ALL
SELECT * FROM DEPT;
SELECT * FROM MEMBER ORDER BY MEMBER_ID DESC;
SELECT DISTINCT DEPT_ID, NAME FROM MEMBER;

SELECT * FROM MEMBER;
SELECT LENGTH(SAL) FROM MEMBER;
SELECT NAME, LENGTH(SAL) FROM MEMBER;
SELECT REPLACE(NAME, '홍', '홍2') FROM MEMBER;
SELECT CONCAT(NAME, '는 한국사람입니다') FROM MEMBER;
SELECT NAME || '는 월급이 '|| sal || '입니다.' FROM MEMBER;

SELECT name, sal FROM MEMBER 
WHERE sal NOT BETWEEN 14000 AND 30000;

SELECT member_id, name, sal, sal * 1.20 AS newsal FROM MEMBER;
SELECT name, MONTHS_BETWEEN(SYSDATE,hire) FROM MEMBER;
SELECT name, ROUND(MONTHS_BETWEEN(SYSDATE,hire),2) FROM MEMBER;
SELECT name, LPAD(sal, 10, '#') FROM MEMBER;

SELECT SYSDATE, TO_CHAR(SYSDATE, 'YYYY-MM-DD') 
FROM dual;
SELECT HIRE, TO_CHAR(hire, 'YYYY-MM-DD') FROM MEMBER;
SELECT HIRE, TO_CHAR(hire, 'YYYY.MM.DD') FROM MEMBER;
SELECT TO_CHAR(hire,'YYYY') FROM MEMBER;
SELECT * FROM MEMBER WHERE TO_CHAR(hire, 'YYYY') = '2000';
SELECT SUM(NVL(bonus, 0)) FROM MEMBER;

SELECT member_id, name, hire, 
TO_CHAR(ADD_MONTHS(hire, 10), 'YYYY-MM-DD') 
FROM member;
SELECT name, jikwi, 
DECODE(jikwi, 
'사장', 'A', 
'부장', 'B', 
'과장', 'C',
'대리', 'D',
'E') "등급"
FROM MEMBER;
-- sal x 12 + bonus
SELECT name, sal * 12 + NVL(bonus, 0) FROM MEMBER;
SELECT member_id, name FROM MEMBER
WHERE TO_CHAR(hire, 'YYYY') = '2004';
SELECT name, jikwi FROM MEMBER WHERE mgr IS NULL;
SELECT name, sal, bonus FROM MEMBER 
WHERE bonus IS NOT NULL ORDER BY bonus DESC;





